services:
  - type: web
    name: deepseek-test
    runtime: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gevent --workers 1 app:app"